name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "16.x"
          - "18.x"
          - "20.5"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Test
        run: npm run ci cjs esm

  test-v20_6_0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "20.x"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Test
        run: npm run ci v20_6_0

  test-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: npm run ci package

  publish:
    needs:
      - test
      - test-v20_6_0
      - test-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/"
      - name: Pin package version
        run: |
          git config user.name ${{ secrets.GIT_USER_NAME }}
          git config user.email ${{ secrets.GIT_USER_EMAIL }}
          npm version --allow-same-version ${GITHUB_REF#refs/*/}
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
